package pl.edu.pjatk.tau.labone.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.List;
import org.springframework.stereotype.Component;
import pl.edu.pjatk.tau.labone.domain.Product;

@Component
public class ProductServiceImpl  implements ProductService {
    private Connection connection;
    private PreparedStatement addProductStmt;
    private PreparedStatement getAllProductsStmt;
    private PreparedStatement deleteProductStmt;
    private PreparedStatement getProductStmt;
    private PreparedStatement updateProductStmt;
    private PreparedStatement deleteAllProductsStmt;

    public ProductServiceImpl(Connection connection) throws SQLException {
        this.connection = connection;
        if (!isDatabaseReady()) {
            createTables();
        }
        setConnection(connection);
    }

    public ProductServiceImpl() throws SQLException {
        this.connection = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");
        if (!isDatabaseReady()) {
            createTables();
        }
        setConnection(this.connection);
    }

    @Override
    public Connection getConnection() {
        return this.connection;
    }

    @Override
    public void setConnection(Connection connection) throws SQLException {
        this.connection = connection;
        this.addProductStmt = connection.prepareStatement("INSERT INTO Product (name, price) VALUES (?, ?)", Statement.RETURN_GENERATED_KEYS);
        this.deleteProductStmt = connection.prepareStatement("DELETE FROM Product where id = ?");
        this.deleteAllProductsStmt = connection.prepareStatement("DELETE FROM Product");
        this.getAllProductsStmt = connection.prepareStatement("SELECT id, name, price FROM Product ORDER BY id");
        this.getProductStmt = connection.prepareStatement("SELECT id, name, price FROM Product WHERE id = ?");
        this.updateProductStmt = connection.prepareStatement("UPDATE Product SET name=?,price=? WHERE id = ?");
    }

    public void createTables() throws SQLException {
        this.connection.createStatement().executeUpdate("CREATE TABLE Product(id int GENERATED BY DEFAULT AS IDENTITY, name varchar(255) NOT NULL, price double)");
    }

    public boolean isDatabaseReady() {
        try {
            ResultSet rs = this.connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next()) {
                if ("Product".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }
            return tableExists;
        } catch (SQLException e) {
            return false;
        }
    }

    @Override
    public int addProduct(Product p) {
        int count = 0;
        try {
            this.addProductStmt.setString(1, p.getName());
            this.addProductStmt.setBigDecimal(2, p.getPrice());
            count = this.addProductStmt.executeUpdate();
            ResultSet generatedKeys = this.addProductStmt.getGeneratedKeys();
            if (generatedKeys.next()) {
                p.setId(generatedKeys.getInt(1));
            }
        } catch (SQLException e) {
            throw new IllegalStateException(e.getMessage() + "\n" + e.getStackTrace().toString());
        }
        return count;
    }

    @Override
    public int deleteProduct(Product p) {
        try {
            this.deleteProductStmt.setInt(1, p.getId());
            return this.deleteProductStmt.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException(e.getMessage() + "\n" + e.getStackTrace().toString());
        }
    }

    @Override
    public int updateProduct(Product p) throws SQLException {
        int count = 0;
        try {
            this.updateProductStmt.setString(1, p.getName());
            this.updateProductStmt.setBigDecimal(2, p.getPrice());
            this.updateProductStmt.setInt(3, p.getId());
            count = this.updateProductStmt.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException(e.getMessage() + "\n" + e.getStackTrace().toString());
        }
        if (count <= 0)
            throw new SQLException("Product not found for update");
        return count;
    }

    @Override
    public Product getProduct(int id) throws SQLException {
        try {
            this.getProductStmt.setInt(1, id);
            ResultSet rs = this.getProductStmt.executeQuery();
            if(rs.next()) {
                Product p = new Product();
                p.setId(rs.getInt("id"));
                p.setName(rs.getString("name"));
                p.setPrice(rs.getBigDecimal("price"));
                return p;
            }
        } catch (SQLException e) {
            throw new IllegalStateException((e.getMessage() + "\n" + e.getStackTrace().toString()));
        }
        throw new SQLException("Product with id " + id + " does not exist");
    }

    @Override
    public int deleteAll() {
        try {
            return this.deleteAllProductsStmt.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException(e.getMessage() + "\n" + e.getStackTrace().toString());
        }
    }

    @Override
    public List<Product> getAll() {
        List<Product> products = new LinkedList<>();
        try {
            ResultSet rs = this.getAllProductsStmt.executeQuery();
            while (rs.next()) {
                Product p = new Product();
                p.setId(rs.getInt("id"));
                p.setName(rs.getString("name"));
                p.setPrice(rs.getBigDecimal("price"));
                products.add(p);
            }
        } catch (SQLException e) {
            throw new IllegalStateException(e.getMessage() + "\n" + e.getStackTrace().toString());
        }
        return products;
    }
}
